### ISSUE TITLE
Scroll bars appear in the pop-up if the text area has over 18 lines and the browser windows is resized in a certain way when attaching a screenshot

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/webcompat-blipz-experiment#116]
**[Affected versions]:**
- Firefox 60.0.2
- Firefox 61.0 

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux 

**[Prerequisites]:**
- Have the "Webcompat Blipz Experiment" installed from https://bugzilla.mozilla.org/attachment.cgi?id=8986213&action=edit
- Have the "extensions.webcompat-blipz-experiment.variation" pref created in "about:config" with the value "more-context"
- Have the browser resized so that the height is close to the width.

**[Steps to reproduce]:**
1. Open the browser from the prerequisites and navigate to https://www.google.com/.
2. Press Alt+Shift+P and click the "No" button.
3. Click the "Attach a screenshot" button.
4. Insert text with over 18 lines into the "Description" box.
5. Observe the pop-up.

**[Expected result]:**
- The pop-up is resized, a vertical scroll bar appears for the "Description" box area, and all elements are visible.

**[Actual result]:**
- The pop-up is resized, a vertical scroll bar appears for the "Description" box area and a horizontal and vertical scroll bar appear for the pop-up area. The "Cancel" and "Submit" buttons are not visible.

**[Notes]:**
- This issue is also reproducible with other variations ("no-context" and "little-context").
- This issue is also reproducible on the "Feedback details" slide.
- The closer the value of the height is to the value of the width, the easier it is to reproduce this issue.  
- Attached a screenshot of the issue:

![rec of issue - scroll bars](https://user-images.githubusercontent.com/37875464/41723438-b98b3990-7573-11e8-9c51-78a539d84e5c.gif)

**Comment by wisniewskit** [comment]
@Softvision-AndreeaCupsa, this should now be fixed in the latest code (testing on beta will have to wait until we get a signed XPI update).

**Comment by Softvision-AndreeaCupsa** [comment]
I have retested this issue on Windows 10 64bit, Mac 10.13 and Arch Linux on Firefox Release(60.0.2) and Firefox Beta Unbranded (61.0b14) with the experiment installed through "about:debugging". 

It seems fixed on Windows 10 64bit and Mac 10.13, but is still reproducible on Arch Linux.

**Comment by wisniewskit** [comment]
Oh lovely. Then this is overly sensitive on default system font sizes, and I'll have to revamp how the frame is rendered to account for it. @miketaylr, do you feel this is something we ought to get right before we ship? I'm hoping I can finish it today, but it might end up being a pain.

**Comment by miketaylr** [comment]
I don't think we should block on something that affects arch, no.

**Comment by wisniewskit** [comment]
I haven't been able to reproduce this since changing the merged code, and based on what I understand that's the "right" way to avoid scrollbars. As such, I'm closing this for now.
